import Link from "next/link";
import { ArrowUpRight, FolderKanban } from "lucide-react";
import { dateValue, labelize, statusValue, stringValue, type DashboardRow } from "@/components/dashboard/dashboard-utils";
import { EmptyState, WidgetError } from "@/components/dashboard/empty-state";
import { WidgetSkeleton } from "@/components/dashboard/loading-skeletons";

export function RecentProjects({ projects, clients, team, isLoading, isError }: { projects: DashboardRow[]; clients: DashboardRow[]; team: DashboardRow[]; isLoading: boolean; isError: boolean }) {
  const recent = [...projects].sort((a, b) => (dateValue(b, ["updated_at", "created_at"])?.getTime() ?? 0) - (dateValue(a, ["updated_at", "created_at"])?.getTime() ?? 0)).slice(0, 5);
  const find = (rows: DashboardRow[], id: unknown) => rows.find((row) => String(row.id ?? "") === String(id ?? ""));
  return <section className="cfy-card"><div className="cfy-card-head flex items-center justify-between"><div><h2 className="text-sm font-semibold tracking-[-.015em] text-zinc-100">Recent projects</h2><p className="mt-1 text-xs text-zinc-500">The latest work across your workspace</p></div><Link href="/workspace/projects" className="cfy-icon-button size-8" aria-label="View projects"><ArrowUpRight className="size-4" /></Link></div>{isLoading ? <WidgetSkeleton rows={5} /> : isError ? <WidgetError /> : !recent.length ? <EmptyState icon={FolderKanban} title="No projects yet" description="Projects will appear here as your team starts work." /> : <div className="divide-y divide-white/[.06]">{recent.map((project, index) => { const status = statusValue(project); const update = dateValue(project, ["updated_at", "created_at"]); const client = find(clients, project.client_id ?? project.client); const editor = find(team, project.editor_id ?? project.assignee_id ?? project.owner_id); return <Link href={`/workspace/projects/${String(project.id ?? "")}`} key={String(project.id ?? index)} className="cfy-list-row flex items-center gap-3 px-5 py-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-[13px] border border-violet-300/[.12] bg-violet-400/[.09] text-xs font-semibold text-violet-100">{stringValue(project, ["name", "title"], "P").slice(0, 1).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-zinc-200">{stringValue(project, ["name", "title", "project_name"])}</p><p className="mt-1 truncate text-xs text-zinc-500">{stringValue(client ?? project, ["name", "company", "client_name"], "No client")} <span className="text-zinc-700">·</span> {editor ? stringValue(editor, ["name", "full_name", "email"], "Editor") : "Unassigned"}</p></div><div className="hidden text-right sm:block"><span className="cfy-status">{labelize(status)}</span><p className="mt-1.5 text-[10px] text-zinc-600">{update ? update.toISOString().slice(0, 10) : "Recently"}</p></div></Link>; })}</div>}</section>;
}
