"use client";

import Link from "next/link";
import { useMemo, useSyncExternalStore } from "react";
import { CalendarClock } from "lucide-react";
import { dateValue, stringValue, type DashboardRow } from "@/components/dashboard/dashboard-utils";
import { EmptyState, WidgetError } from "@/components/dashboard/empty-state";
import { WidgetSkeleton } from "@/components/dashboard/loading-skeletons";

const priorityClass: Record<string, string> = { urgent: "text-rose-200 border-rose-300/15 bg-rose-400/[.08]", high: "text-amber-100 border-amber-300/15 bg-amber-300/[.07]", medium: "text-violet-200 border-violet-300/15 bg-violet-400/[.08]", low: "text-zinc-400 border-white/[.08] bg-white/[.04]" };

export function UpcomingDeadlines({ deliverables, tasks, events, projects, clients, team, isLoading, isError }: { deliverables: DashboardRow[]; tasks: DashboardRow[]; events: DashboardRow[]; projects: DashboardRow[]; clients: DashboardRow[]; team: DashboardRow[]; isLoading: boolean; isError: boolean }) {
  const mounted = useSyncExternalStore(() => () => undefined, () => true, () => false);
  const items = useMemo(() => { const all = [...deliverables, ...tasks, ...events].map((item) => ({ item, date: dateValue(item, ["due_date", "deadline", "due_at", "end_at", "event_date"]) })).filter((item): item is { item: DashboardRow; date: Date } => Boolean(item.date)).sort((a, b) => a.date.getTime() - b.date.getTime()); return mounted ? all.filter(({ date }) => date >= new Date()).slice(0, 5) : all.slice(0, 5); }, [deliverables, events, mounted, tasks]);
  const find = (rows: DashboardRow[], id: unknown) => rows.find((row) => String(row.id ?? "") === String(id ?? ""));
  return <section className="cfy-card"><div className="cfy-card-head"><h2 className="text-sm font-semibold tracking-[-.015em] text-zinc-100">Upcoming deadlines</h2><p className="mt-1 text-xs text-zinc-500">The next milestones on your calendar</p></div>{isLoading ? <WidgetSkeleton rows={4} /> : isError ? <WidgetError /> : !items.length ? <EmptyState icon={CalendarClock} title="No upcoming deadlines" description="Due tasks, deliverables, and calendar events will appear here." /> : <div className="divide-y divide-white/[.06]">{items.map(({ item, date }, index) => { const project = find(projects, item.project_id); const client = find(clients, item.client_id ?? project?.client_id); const editor = find(team, item.editor_id ?? item.assignee_id ?? item.user_id); const priority = stringValue(item, ["priority"], "medium").toLowerCase(); const projectId = String(item.project_id ?? project?.id ?? ""); const content = <><span className="flex size-10 shrink-0 flex-col items-center justify-center rounded-[13px] border border-white/[.08] bg-white/[.035] text-[10px] leading-3 text-zinc-400"><strong className="text-xs font-semibold text-zinc-100">{date.getUTCDate()}</strong>{["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][date.getUTCMonth()]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-zinc-200">{stringValue(project ?? item, ["name", "title", "project_name", "task_name", "deliverable_name"])}</p><p className="mt-1 truncate text-xs text-zinc-500">{stringValue(client ?? item, ["name", "company", "client_name"], "No client")} <span className="text-zinc-700">·</span> {editor ? stringValue(editor, ["name", "full_name", "email"], "Editor") : "Unassigned"}</p></div><div className="hidden text-right sm:block"><p className="text-xs text-zinc-400">{date.toISOString().slice(0, 10)}</p><span className={`mt-1 inline-flex rounded-full border px-2 py-0.5 text-[10px] ${priorityClass[priority] ?? priorityClass.medium}`}>{priority}</span></div></>; return projectId ? <Link className="cfy-list-row flex items-center gap-3 px-5 py-4" href={`/workspace/projects/${projectId}`} key={String(item.id ?? index)}>{content}</Link> : <div className="cfy-list-row flex items-center gap-3 px-5 py-4" key={String(item.id ?? index)}>{content}</div>; })}</div>}</section>;
}
