"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Archive, AtSign, BellRing, Check, CheckCheck, ChevronDown, CircleAlert, CircleCheck, ClipboardCheck, Clock3, FileUp, Filter, Info, MessageSquare, Search, Settings2, Trash2, UserPlus, X } from "lucide-react";
import { toast } from "sonner";
import { z } from "zod";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { DashboardSidebar } from "@/components/dashboard/dashboard-sidebar";
import { dateValue, labelize, relativeDate, rows, stringValue, type DashboardRow } from "@/components/dashboard/dashboard-utils";
import { type NotificationFilter, useNotificationsData } from "@/hooks/use-notifications-data";
import { useTableList } from "@/hooks/use-table";
import { EmptyState } from "@/components/ui/empty-state";

const filters: { value: NotificationFilter; label: string }[] = [{ value: "all", label: "All notifications" }, { value: "unread", label: "Unread" }, { value: "mentions", label: "Mentions" }, { value: "assignments", label: "Assignments" }, { value: "approvals", label: "Approvals" }];
const settingsSchema = z.object({ email: z.boolean(), desktop: z.boolean(), digest: z.boolean() });

export function NotificationsContent({ email }: { email: string | null }) {
  const workspaces = useTableList("workspaces");
  const [filter, setFilter] = useState<NotificationFilter>("all");
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const center = useNotificationsData(filter, debouncedSearch);
  const { fetchNextPage, hasNextPage, isFetchingNextPage } = center.notifications;
  const sentinel = useRef<HTMLDivElement>(null);
  const notifications = center.notifications.data?.pages.flatMap((page) => page.rows).map(asRow) ?? [];
  const activity = rows(center.activity.data);
  const total = center.notifications.data?.pages[0]?.count ?? 0;
  const unread = notifications.filter((item) => !isRead(item)).length;

  useEffect(() => { const timeout = window.setTimeout(() => setDebouncedSearch(search), 250); return () => window.clearTimeout(timeout); }, [search]);
  useEffect(() => {
    const node = sentinel.current;
    if (!node || !hasNextPage) return;
    const observer = new IntersectionObserver((entries) => { if (entries[0]?.isIntersecting && !isFetchingNextPage) void fetchNextPage(); }, { rootMargin: "240px" });
    observer.observe(node); return () => observer.disconnect();
  }, [fetchNextPage, hasNextPage, isFetchingNextPage]);

  const markRead = async (id: string) => { try { await center.markRead.mutateAsync(id); toast.success("Marked as read"); } catch { toast.error("Couldn’t update this notification."); } };
  const markAllRead = async () => { try { await center.markAllRead.mutateAsync(); toast.success("All notifications marked as read"); } catch { toast.error("Couldn’t mark all notifications as read."); } };
  const remove = async (id: string) => { try { await center.remove.mutateAsync(id); toast.success("Notification removed"); } catch { toast.error("Couldn’t remove this notification."); } };

  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="cfy-shell text-zinc-100 lg:flex"><DashboardSidebar email={email} /><div className="min-w-0 flex-1"><DashboardHeader workspaces={rows(workspaces.data)} /><main className="relative mx-auto w-full max-w-[1560px] px-4 py-7 sm:px-6 lg:px-8 xl:px-10"><header className="cfy-fade-up flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-violet-300/75">Workspace signal center</p><div className="mt-2 flex flex-wrap items-baseline gap-x-3 gap-y-1"><h1 className="text-3xl font-semibold tracking-[-.055em] text-white sm:text-[2.25rem]">Notifications & activity</h1><span className="text-sm text-zinc-500">One calm, continuous view of work.</span></div><p className="mt-2 text-sm text-zinc-500">Live workspace signals, approvals, mentions, and delivery movement.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setSettingsOpen(true)} className="cfy-icon-button h-10 gap-2 px-3 text-xs text-zinc-300"><Settings2 className="size-3.5" />Settings</button><button disabled={!unread || center.markAllRead.isPending} onClick={markAllRead} className="cfy-primary-button h-10 px-3.5 disabled:cursor-not-allowed disabled:opacity-50"><CheckCheck className="size-3.5" />Mark all read</button></div></header>
    <NotificationWidgets notifications={notifications} activity={activity} />
    <section className="cfy-card cfy-fade-up cfy-fade-up-delay-2 mt-6"><div className="flex flex-col gap-3 border-b border-white/[.06] px-4 py-4 lg:flex-row lg:items-center lg:justify-between sm:px-5"><div className="flex min-w-0 flex-1 flex-col gap-3 sm:flex-row"><label className="cfy-control flex h-10 min-w-0 items-center gap-2 px-3 sm:max-w-md sm:flex-1"><Search className="size-4 shrink-0 text-zinc-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search title, detail, or context…" className="min-w-0 flex-1 bg-transparent text-sm text-zinc-200 outline-none placeholder:text-zinc-600" /></label><div className="cfy-control flex h-10 items-center gap-2 px-3"><Filter className="size-3.5 text-zinc-500" /><select aria-label="Filter notifications" value={filter} onChange={(event) => setFilter(event.target.value as NotificationFilter)} className="min-w-36 bg-transparent text-xs text-zinc-300 outline-none">{filters.map((item) => <option className="bg-zinc-900" key={item.value} value={item.value}>{item.label}</option>)}</select><ChevronDown className="size-3.5 text-zinc-500" /></div></div><span className="text-xs text-zinc-500">{total} signal{total === 1 ? "" : "s"} · <span className="text-violet-200">{unread} unread</span></span></div>
      {center.notifications.isLoading ? <NotificationSkeleton /> : center.notifications.isError ? <LoadError onRetry={() => void center.notifications.refetch()} /> : !notifications.length ? <EmptyNotifications filter={filter} search={search} onRefresh={() => void center.notifications.refetch()} /> : <div className="divide-y divide-white/[.06]">{notifications.map((notification, index) => <NotificationRow key={rowId(notification) || index} notification={notification} onMarkRead={markRead} onDelete={remove} busy={center.markRead.isPending || center.remove.isPending} />)}</div>}
      <div ref={sentinel} className="flex min-h-16 items-center justify-center border-t border-white/[.06] p-3">{isFetchingNextPage ? <span className="flex items-center gap-2 text-xs text-zinc-500"><span className="size-2 animate-pulse rounded-full bg-violet-300" />Loading older signals…</span> : hasNextPage ? <button onClick={() => void fetchNextPage()} className="cfy-icon-button h-8 px-3 text-xs">Load older notifications</button> : notifications.length > 0 ? <span className="text-xs text-zinc-600">You’re at the beginning of the timeline.</span> : null}</div>
    </section>
    <section className="cfy-card cfy-fade-up cfy-fade-up-delay-3 mt-6"><SectionHead icon={<Clock3 className="size-4" />} title="Activity timeline" subtitle="Every workspace event, ordered by most recent." /><ActivityTimeline activity={activity} loading={center.activity.isLoading} error={center.activity.isError} /></section>
  </main></div><AnimatePresence>{settingsOpen && <SettingsModal onClose={() => setSettingsOpen(false)} />}</AnimatePresence></motion.div>;
}

function NotificationWidgets({ notifications, activity }: { notifications: DashboardRow[]; activity: DashboardRow[] }) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const unread = notifications.filter((item) => !isRead(item)).length;
  const mentions = notifications.filter((item) => notificationType(item) === "mention").length;
  const approvals = notifications.filter((item) => notificationType(item) === "approval" && !isRead(item)).length;
  const todayActivity = activity.filter((item) => (dateValue(item, ["created_at", "timestamp", "updated_at"]) ?? new Date(0)) >= today).length;
  return <div className="cfy-fade-up cfy-fade-up-delay-1 mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Widget icon={<BellRing className="size-4" />} label="Unread notifications" value={unread} detail={unread ? "Need your attention" : "You’re all caught up"} accent="violet" /><Widget icon={<Clock3 className="size-4" />} label="Today’s activity" value={todayActivity} detail="Workspace events today" accent="cyan" /><Widget icon={<AtSign className="size-4" />} label="Recent mentions" value={mentions} detail="Direct collaboration signals" accent="amber" /><Widget icon={<ClipboardCheck className="size-4" />} label="Pending approvals" value={approvals} detail="Awaiting your decision" accent="emerald" /></div>;
}
function Widget({ icon, label, value, detail, accent }: { icon: ReactNode; label: string; value: number; detail: string; accent: string }) { const colors: Record<string, string> = { violet: "bg-violet-400/[.12] text-violet-200", cyan: "bg-cyan-400/[.10] text-cyan-200", amber: "bg-amber-400/[.10] text-amber-100", emerald: "bg-emerald-400/[.10] text-emerald-200" }; return <article className="cfy-kpi"><span className={`flex size-9 items-center justify-center rounded-[13px] ${colors[accent]}`}>{icon}</span><p className="mt-5 text-[11px] font-medium uppercase tracking-[.13em] text-zinc-500">{label}</p><div className="mt-1 flex items-end justify-between gap-3"><p className="text-2xl font-semibold tracking-[-.04em] text-zinc-100">{value}</p><p className="mb-1 text-right text-[11px] text-zinc-500">{detail}</p></div></article>; }
function NotificationRow({ notification, onMarkRead, onDelete, busy }: { notification: DashboardRow; onMarkRead: (id: string) => void; onDelete: (id: string) => void; busy: boolean }) { const id = rowId(notification); const read = isRead(notification); const type = notificationType(notification); const context = stringValue(notification, ["project_name", "client_name", "related_name", "project", "client"], "Workspace"); const action = stringValue(notification, ["action_label", "action", "cta_label"], "Review"); return <motion.article layout initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: -12 }} className={`cfy-list-row group flex gap-3 px-4 py-4 sm:px-5 ${read ? "" : "bg-violet-400/[.045]"}`}><span className={`mt-0.5 flex size-10 shrink-0 items-center justify-center rounded-[14px] ${iconColor(type)}`}><NotificationIcon type={type} /></span><div className="min-w-0 flex-1"><div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between sm:gap-4"><p className={`truncate text-sm ${read ? "text-zinc-300" : "font-semibold text-zinc-100"}`}>{stringValue(notification, ["title", "subject", "name"], "Workspace notification")}</p><span className="shrink-0 text-[11px] text-zinc-500">{relativeDate(dateValue(notification, ["created_at", "timestamp", "updated_at"]))}</span></div><p className="mt-1 max-w-3xl text-sm leading-5 text-zinc-500">{stringValue(notification, ["description", "message", "body", "content"], "There’s an update in your workspace.")}</p><div className="mt-3 flex flex-wrap items-center gap-2"><Avatar notification={notification} /><span className="cfy-badge py-0.5 text-[10px]">{context}</span><span className="cfy-badge py-0.5 text-[10px]"><span className={`size-1.5 rounded-full ${typeDot(type)}`} />{labelize(type)}</span></div></div><div className="flex shrink-0 items-start gap-1"><button onClick={() => toast.info(`${action} is ready in the related workspace record.`)} className="cfy-icon-button hidden h-8 px-2 text-[11px] sm:flex">{action}</button>{!read && <button disabled={busy} onClick={() => onMarkRead(id)} aria-label="Mark notification as read" className="cfy-icon-button size-8" title="Mark as read"><Check className="size-3.5" /></button>}<button disabled={busy} onClick={() => onDelete(id)} aria-label="Delete notification" className="cfy-icon-button size-8 text-zinc-500 hover:text-red-200"><Trash2 className="size-3.5" /></button></div></motion.article>; }
function ActivityTimeline({ activity, loading, error }: { activity: DashboardRow[]; loading: boolean; error: boolean }) { const timeline = useMemo(() => [...activity].sort((a, b) => (dateValue(b, ["created_at", "timestamp", "updated_at"])?.getTime() ?? 0) - (dateValue(a, ["created_at", "timestamp", "updated_at"])?.getTime() ?? 0)), [activity]); if (loading) return <div className="space-y-3 p-5">{Array.from({ length: 6 }, (_, index) => <div key={index} className="cfy-skeleton h-14" />)}</div>; if (error) return <LoadError />; if (!timeline.length) return <div className="flex min-h-60 flex-col items-center justify-center p-6 text-center"><Clock3 className="size-7 text-zinc-600" /><p className="mt-3 text-sm font-medium text-zinc-300">No activity recorded yet</p><p className="mt-1 text-xs text-zinc-500">Project changes, uploads, approvals, and team events will appear here.</p></div>; return <div className="p-4 sm:p-5"><div className="space-y-1 border-l border-white/[.08]">{timeline.map((item, index) => { const kind = stringValue(item, ["event_type", "action", "type", "activity_type"], "activity"); return <div key={rowId(item) || index} className="relative ml-5 flex gap-3 py-3 first:pt-0"><span className="absolute -left-[26px] top-4 flex size-3 items-center justify-center rounded-full border-2 border-[#19191e] bg-violet-300 first:top-1" /><span className="flex size-8 shrink-0 items-center justify-center rounded-xl bg-white/[.045] text-violet-200"><NotificationIcon type={kind} /></span><div className="min-w-0"><p className="text-sm text-zinc-300">{stringValue(item, ["description", "message", "action", "event_type"], "Workspace activity updated")}</p><p className="mt-1 text-xs text-zinc-500">{stringValue(item, ["actor_name", "user_name", "created_by_name"], "Workspace") } · {relativeDate(dateValue(item, ["created_at", "timestamp", "updated_at"]))}</p></div></div>; })}</div></div>; }
function SettingsModal({ onClose }: { onClose: () => void }) { const [settings, setSettings] = useState(() => ({ email: true, desktop: true, digest: false })); const save = () => { const parsed = settingsSchema.safeParse(settings); if (!parsed.success) return toast.error("Review notification preferences."); window.localStorage.setItem("contendfy-notification-preferences", JSON.stringify(parsed.data)); toast.success("Notification preferences saved"); onClose(); }; return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 flex items-end bg-black/60 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-5"><motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 14 }} className="cfy-modal w-full max-w-md"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold text-white">Notification settings</h2><p className="mt-1 text-sm text-zinc-500">Choose how workspace signals reach you.</p></div><button onClick={onClose} className="cfy-icon-button size-8"><X className="size-4" /></button></div><div className="mt-6 space-y-2">{([ ["email", "Email notifications", "Important approvals and assignment changes."], ["desktop", "Desktop alerts", "Real-time signals while this workspace is open."], ["digest", "Daily digest", "A concise daily activity summary."] ] as const).map(([key, title, description]) => <label key={key} className="flex cursor-pointer items-center gap-3 rounded-[16px] border border-white/[.07] bg-white/[.025] p-3.5"><input type="checkbox" checked={settings[key]} onChange={(event) => setSettings({ ...settings, [key]: event.target.checked })} className="size-4 accent-violet-300" /><span><span className="block text-sm font-medium text-zinc-200">{title}</span><span className="mt-0.5 block text-xs leading-5 text-zinc-500">{description}</span></span></label>)}</div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="cfy-icon-button h-10 px-4 text-sm">Cancel</button><button onClick={save} className="cfy-primary-button h-10 px-4">Save preferences</button></div></motion.div></motion.div>; }
function SectionHead({ icon, title, subtitle }: { icon: ReactNode; title: string; subtitle: string }) { return <div className="cfy-card-head flex items-start gap-3"><span className="mt-0.5 text-violet-200">{icon}</span><span><h2 className="text-sm font-semibold tracking-[-.015em] text-zinc-100">{title}</h2><p className="mt-1 text-xs text-zinc-500">{subtitle}</p></span></div>; }
function NotificationSkeleton() { return <div className="space-y-2 p-4">{Array.from({ length: 7 }, (_, index) => <div key={index} className="cfy-skeleton h-[104px]" />)}</div>; }
function EmptyNotifications({ filter, search, onRefresh }: { filter: NotificationFilter; search: string; onRefresh: () => void }) { if (search || filter !== "all") return <EmptyState kind="notifications" title="No Matching Notifications" description="Try a different search term or clear the current filter to see more workspace activity." primary={{ label: "Go to dashboard", href: "/workspace" }} secondary={{ label: "Refresh", onClick: onRefresh }} className="min-h-80" />; return <EmptyState kind="notifications" title="You’re All Caught Up" description="There are no new notifications. Updates, mentions, and activity will appear here." primary={{ label: "Go to dashboard", href: "/workspace" }} secondary={{ label: "Refresh", onClick: onRefresh }} className="min-h-80" />; }
function LoadError({ onRetry }: { onRetry?: () => void }) { return <div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><CircleAlert className="size-7 text-red-300" /><p className="mt-3 font-medium text-zinc-200">Unable to load notifications</p><p className="mt-1 text-sm text-zinc-500">Check your connection and try again.</p>{onRetry && <button onClick={onRetry} className="cfy-icon-button mt-4 h-9 px-3 text-xs">Try again</button>}</div>; }
function Avatar({ notification }: { notification: DashboardRow }) { const name = stringValue(notification, ["actor_name", "user_name", "sender_name", "created_by_name"], "Workspace"); return <span title={name} className="flex size-5 items-center justify-center rounded-full bg-zinc-700 text-[8px] font-semibold text-zinc-200">{name.slice(0, 2).toUpperCase()}</span>; }
function rowId(row: DashboardRow) { return String(row.id ?? ""); }
function asRow(row: Record<string, unknown>) { return row as DashboardRow; }
function isRead(row: DashboardRow) { return Boolean(row.is_read ?? row.read_at ?? row.read); }
function notificationType(row: DashboardRow) { const value = stringValue(row, ["type", "notification_type", "category", "kind"], "system").toLowerCase(); return value.replace(/[^a-z]/g, "") || "system"; }
function NotificationIcon({ type }: { type: string }) { const classes = "size-4"; if (type.includes("success") || type.includes("approval")) return <CircleCheck className={classes} />; if (type.includes("warning") || type.includes("reminder") || type.includes("error")) return <CircleAlert className={classes} />; if (type.includes("mention")) return <AtSign className={classes} />; if (type.includes("assign")) return <ClipboardCheck className={classes} />; if (type.includes("comment")) return <MessageSquare className={classes} />; if (type.includes("upload") || type.includes("file")) return <FileUp className={classes} />; if (type.includes("invite")) return <UserPlus className={classes} />; if (type.includes("archive")) return <Archive className={classes} />; return <Info className={classes} />; }
function iconColor(type: string) { if (type.includes("error")) return "bg-red-400/[.11] text-red-200"; if (type.includes("warning") || type.includes("reminder")) return "bg-amber-400/[.11] text-amber-100"; if (type.includes("approval") || type.includes("success")) return "bg-emerald-400/[.11] text-emerald-200"; if (type.includes("mention")) return "bg-cyan-400/[.11] text-cyan-200"; return "bg-violet-400/[.12] text-violet-200"; }
function typeDot(type: string) { if (type.includes("error")) return "bg-red-300"; if (type.includes("warning") || type.includes("reminder")) return "bg-amber-300"; if (type.includes("approval") || type.includes("success")) return "bg-emerald-300"; if (type.includes("mention")) return "bg-cyan-300"; return "bg-violet-300"; }
